# Generated by Django 6.1 on 2026-09-07 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_chore'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='assignment_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('rotation', 'Rotation'), ('claim', 'Claim')], default='manual', max_length=8),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('assignment_type', models.CharField(choices=[('manual', 'Manual'), ('claim', 'Claim'), ('rotation', 'Rotation')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.chore')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_assignments', to='chores.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('chore', 'occurrence'), name='unique_active_chore_occurrence_assignment')],
            },
        ),
        migrations.CreateModel(
            name='RotationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_members', to='chores.chore')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_memberships', to='chores.membership')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('chore', 'position'), name='unique_chore_rotation_position'), models.UniqueConstraint(fields=('chore', 'membership'), name='unique_chore_rotation_member')],
            },
        ),
    ]
