# Generated by Django 6.1 on 2026-09-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_chore_assignment_mode_membership_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='assignment_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('rotation', 'Rotation'), ('claim', 'Claim')], max_length=8),
        ),
    ]
