# Generated by Django 6.1 on 2026-09-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_alter_chore_assignment_mode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('assignment_mode__in', ('manual', 'rotation', 'claim'))), name='chore_assignment_mode_allowed_values'),
        ),
    ]
