# Generated by Django 6.1 on 2026-09-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0005_chore_chore_assignment_mode_allowed_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="rotation_position",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
