# Generated by Django 6.1 on 2026-09-07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0006_chore_rotation_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="anchor_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="chore",
            name="fixed_recurrence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("every_n_days", "Every N days"),
                    ("selected_weekdays", "Selected weekdays"),
                ],
                default="daily",
                max_length=18,
            ),
        ),
        migrations.AddField(
            model_name="chore",
            name="recurrence_interval_days",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="chore",
            name="recurrence_mode",
            field=models.CharField(
                choices=[("fixed", "Fixed/calendar"), ("flexible", "Flexible")],
                default="fixed",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="chore",
            name="selected_weekdays",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
