# Generated by Django 6.1 on 2026-09-07 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_chore_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=9)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='chores.choreassignment')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.chore')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.household')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_completions', to='chores.membership')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_completions', to='chores.membership')),
            ],
            options={
                'ordering': ['-submitted_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'approved'))), fields=('chore', 'occurrence'), name='unique_open_completion_occurrence'), models.UniqueConstraint(condition=models.Q(('status', 'rejected')), fields=('chore', 'occurrence', 'submitted_by'), name='unique_rejected_completion_submitter')],
            },
        ),
    ]
