# Generated by Django 6.1 on 2026-09-07 02:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_ledger_entries', to='chores.chore')),
                ('completion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='points_ledger_entry', to='chores.completion')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_ledger_entries', to='chores.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_ledger_entries', to='chores.membership')),
            ],
            options={
                'ordering': ['-awarded_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('completion',), name='unique_points_ledger_completion')],
            },
        ),
    ]
