# Generated by Django 6.1 on 2026-09-07 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0009_pointsledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_activity_days', to='chores.household')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_days', to='chores.membership')),
            ],
            options={
                'ordering': ['activity_date'],
                'constraints': [models.UniqueConstraint(fields=('membership', 'activity_date'), name='unique_member_activity_day')],
            },
        ),
        migrations.CreateModel(
            name='MemberStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='streak', to='chores.membership')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('current_streak__gte', 0), ('best_streak__gte', 0)), name='member_streak_non_negative')],
            },
        ),
    ]
