# Generated by Django 6.1 on 2026-09-07 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_memberactivityday_memberstreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberactivityday',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_activity_days', to='chores.household'),
        ),
        migrations.AlterField(
            model_name='memberactivityday',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to='chores.membership'),
        ),
        migrations.AlterField(
            model_name='memberstreak',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='chores.membership'),
        ),
    ]
