# Generated by Django 6.1 on 2026-09-07 02:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0011_alter_memberactivityday_household_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_identifier', models.CharField(max_length=40)),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badge_awards', to='chores.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badge_awards', to='chores.membership')),
            ],
            options={
                'ordering': ['-awarded_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('member', 'badge_identifier'), name='unique_member_badge_award')],
            },
        ),
    ]
